### PR TITLE
Update dependencies and webpack config

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Thanks a lot! I will try out the goodness :smile:

**Comment by Zaid-Ajaj** [comment]
The watch compilation works and the tests pass! but when I make changes to the tests file I get this error:
```
Compiling...
Parsing ./Tests.fs...
fable: Compiled test\Tests.fs
× ｢wdm｣: Hash: e3fada801b191294c36c
Version: webpack 4.10.2
Time: 817ms
Built at: 2018-06-07 12:27:17
 1 asset
Entrypoint main = bundle.js
[./test/Tests.fs] 51.6 KiB {main} [not cacheable] [built] [2 errors]
    + 45 hidden modules


ERROR in ./test/Tests.fs
startup(1,0): (1,0) error FSHARP: Assembly reference 'C:/projects/simple-json-repro/src/bin/Debug/netstandard2.0/Fable.SimpleJson.dll' was not found or is invalid
 @ ./test/Tests.fsproj 1:0-27 1:0-27
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./test/Tests.fsproj

ERROR in ./test/Tests.fs
startup(1,0): (1,0) error FSHARP: Unable to find the file 'C:/projects/simple-json-repro/src/bin/Debug/netstandard2.0/Fable.SimpleJson.dll' in any of
 C:\Users\zaidn\.nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref
 C:\projects\simple-json-repro\test
 C:\Users\zaidn\.nuget\packages\.tools\dotnet-fable\2.0.0-alpha-015\netcoreapp2.0\
 @ ./test/Tests.fsproj 1:0-27 1:0-27
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./test/Tests.fsproj
i ｢wdm｣: Failed to compile.
```
Also the `build` npm script doesn't seem to work unless I remove the `--` from the script like the following
```
"build": "webpack-cli --mode production"
```

**Comment by alfonsogarciacaro** [comment]
Ah, true! The `--` is only needed if you invoke `webpack-cli` directly from Fable, as in `dotnet fable webpack-cli -- --mode production`. Hmm, I'll check about the Assembly reference error. Thanks for pointing it out!

**Comment by alfonsogarciacaro** [comment]
Hmm, I cannot reproduce the `Assembly reference` error. This is what I do:

```
npm install
cd test
dotnet fable webpack-dev-ser
```

After build is finished I edit the Tests.fs file and when I save the project is recompiled correctly and the tests web is automatically reloaded. My system configuration:

```
macOS
dotnet SDK 2.1.300
```

**Comment by Zaid-Ajaj** [comment]
Hmm, my config:
```
windows 10
dotnet --version => 2.1.201
```
I will update `dotnet` but it is kind of weird, I will let you know what I get

**Comment by alfonsogarciacaro** [comment]
Hmm, I tried with `dotnet SDK 2.1.200` and it worked fine too. I'll check with Windows later. Just in case, can you run `git clean -xfd` and try the steps above again?

**Comment by alfonsogarciacaro** [comment]
@Zaid-Ajaj I can reproduce the "Assembly reference" error in Windows with dotnet SDK 2.1.300. I hate these platform-specific errors 😬 Let's see if it can be fixed somehow...

**Comment by alfonsogarciacaro** [comment]
Luckily I was able to find the issue quickly: I was just relying on `/` to split the file name for project references, which didn't work on Windows. I wonder why this hasn't affected Fable 1 (apparently). Fix coming soon :)

**Comment by alfonsogarciacaro** [comment]
Can you please try with dotnet-fable 2.0.0-alpha-017?

**Comment by Zaid-Ajaj** [comment]
Just compiled in watch mode and it seems to work fine! thanks a lot for fixing this :smile:

**Comment by Zaid-Ajaj** [comment]
BTW, I didn't have to update dotnet, still using `2.1.201`

**Pull request merged**
